name: Lint

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  NODE_VERSION: 18

jobs:
  linting:
    name: Running next lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Clean Install Dependencies
        run: npm ci

      - name: Create .env file
        run: cp .env.example .env

      - name: Code Linting
        run: npm run lint
